# Generated by Django 4.2.7 on 2023-12-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="message",
            new_name="feedback_text",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="email",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="name",
        ),
        migrations.AddField(
            model_name="feedback",
            name="star_rating",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=1
            ),
        ),
    ]
